propel:
  _attributes:      { package: plugins.sfFbConnectGuardPlugin.lib.model }
  sf_fb_connect_guard_user:
    _attributes:    { phpName: sfFbConnectGuardUser }
    user_id:        { type: integer, primaryKey: true, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    fb_uid:  { type: integer }
  
